### ISSUE TITLE
`flynn run <command>` results in hanging

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/flynn-cli#10] opened 2014-04-30 20:42 UTC
When you do a `flynn run <command>`, it succeeds in running the command, but never actually exits.  This results in the command hanging, and not releasing stdout.  This is on a vagrant box running 12.04.

**Comment by lmars** [comment] 2014-05-01 01:01
The issue is that stdin continues to be streamed to the host via the controller, even after the job on the host has finished, unless you explicitly close stdin.

For example, this will hang:

```
$ flynn run date
Thu May  1 00:35:24 UTC 2014

```

Killing the process then leaves the terminal in raw noecho mode (which you can get out of by running `stty icanon echo`)

The following however will return correctly after 1 second (when stdin closes):

```
$ flynn run date < <(sleep 1)
Thu May  1 00:35:36 UTC 2014
$
```

To fix this, the copying of stdin from the client to the host (which happens [here](https://github.com/flynn/flynn-controller/blob/master/jobs.go#L281)) needs to stop once the job finishes, but I am not entirely sure how to do that.

**Comment by lmars** [comment] 2014-05-01 15:24
The terminal being left in raw noecho mode could be fixed by using [github.com/dotcloud/docker/pkg/term](https://github.com/dotcloud/docker/tree/master/pkg/term) (rather than [github.com/heroku/hk/term](https://github.com/heroku/hk/tree/master/term)) as it [restores the terminal after an interrupt](https://github.com/dotcloud/docker/blob/master/pkg/term/term.go#L90)

**Comment by jayd3e** [comment] 2014-05-03 05:26
I haven't looked into this super close, but this looks suspect: https://github.com/flynn/flynn-controller/blob/master/jobs.go#L273.  Is there a reason that channel would need to get received from twice?  If I understand the way channels work correctly, every time a channel is "pushed to" in can optionally "receive" from that channel on the other end?  So that would indicate that done is getting "pushed to" twice, correct?

**Comment by titanous** [comment] 2014-05-03 14:18
@jayd3e yeah, there are two calls to `cp` above and each should send to `done`.

**Comment by jayd3e** [comment] 2014-05-03 18:27
So it's definitely happening in the CLI.  I narrowed it down by completely removing the second call to `cp`, after finding that it's stalling on the second call in the controller.  After removing that call to `cp`, it exits appropriately from the controller, but continues to hang on the client.

So basically, I'm just repeating what @lmars already said earlier about stdin not getting closed somewhere.

**Comment by jayd3e** [comment] 2014-05-03 18:49
Errr I take it back.  I just added some debugging statements to flynn-cli, and both calls to `io.Copy()` don't exit.  So I can only assume that means that a channel isn't getting closed in the controller.

**Comment by chriskilding** [comment] 2014-05-23 15:39
Can confirm this is happening for me too.

I also get a weird gzip error when some commands complete, like this:

```
flynn run rake db:migrate

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Closed as completed** 2017-11-08 16:11 UTC
